name: SonarCloudAnalysis

on:
  push
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: BuildandAnalyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkoutcode
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SetupJDK17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: CacheSonarCloudpackages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: BuildwithMaven
        run: mvn-B verify
      
      - name: SonarCloud Scan
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
         mvnsonar:sonar \
         -Dsonar.projectKey=gajanayagmbs-258868e_lab02 \
         -Dsonar.organization=gajanayagmbs-258868e \
         -Dsonar.host.url=https://sonarcloud.io
